export const CONTACT_USER_REQUEST = "CONTACT_USER_REQUEST";
export const CONTACT_USER_SUCCESS = "CONTACT_USER_SUCCESS";
export const CONTACT_USER_FAIL = "CONTACT_USER_FAIL";

export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const ALL_CONTACT_SUCCESS = "ALL_CONTACT_SUCCESS";
export const ALL_CONTACT_FAIL = "ALL_CONTACT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";