export const ROE_REQUEST = "ROE_REQUEST";
export const ROE_SUCCESS = "ROE_SUCCESS";
export const ROE_FAIL = "ROE_FAIL";


export const ROE_UPDATE_REQUEST = "ROE_UPDATE_REQUEST";
export const ROE_UPDATE_SUCCESS = "ROE_UPDATE_SUCCESS";
export const ROE_UPDATE_RESET = "ROE_UPDATE_RESET";
export const ROE_UPDATE_FAIL = "ROE_UPDATE_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";