export const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_RESET = "CREATE_COUPON_RESET";
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL";

export const ALL_COUPON_REQUEST = "ALL_COUPON_REQUEST";
export const ALL_COUPON_SUCCESS = "ALL_COUPON_SUCCESS";
export const ALL_COUPON_FAIL = "ALL_COUPON_FAIL";


export const VALIDATE_COUPON_REQUEST = "VALIDATE_COUPON_REQUEST";
export const VALIDATE_COUPON_SUCCESS = "VALIDATE_COUPON_SUCCESS";
export const VALIDATE_COUPON_FAIL = "VALIDATE_COUPON_FAIL";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_RESET = "DELETE_COUPON_RESET";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";

export const COUPON_UPDATE_REQUEST = "COUPON_UPDATE_REQUEST";
export const COUPON_UPDATE_SUCCESS = "COUPON_UPDATE_SUCCESS";
export const COUPON_UPDATE_RESET = "COUPON_UPDATE_RESET";
export const COUPON_UPDATE_FAIL = "COUPON_UPDATE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";